export const brandAssets = {
  "Abercrombie & Fitch": "brands/abercrombie-and-fitch.png",
  "Acqua di Parma": "brands/acqua-di-parma.png",
  Armaf: "brands/armaf.png",
  Azzaro: "brands/azzaro.png",
  Bharara: "brands/bharara.png",
  Burberry: "brands/burberry.png",
  Bvlgari: "brands/bvlgari.png",
  "Carolina Herrera": "brands/carolina-herrera.png",
  Casamorati: "brands/casamorati.png",
  Chanel: "brands/chanel.png",
  Creed: "brands/creed.png",
  Dior: "brands/dior.png",
  Diptyque: "brands/diptyque.png",
  "Dolce & Gabbana": "brands/dolce-and-gabbana.png",
  "Essential Parfums": "brands/essential-parfums.png",
  "Giorgio Armani": "brands/giorgio-armani.png",
  Givenchy: "brands/givenchy.png",
  Guerlain: "brands/guerlain.png",
  Guess: "brands/guess.png",
  Halloween: "brands/halloween.png",
  "Hermès": "brands/hermes.png",
  "Hugo Boss": "brands/hugo-boss.png",
  Jaguar: "brands/jaguar.png",
  "Jean Paul Gaultier": "brands/jean-paul-gaultier.png",
  "Jo Milano": "brands/jo-milano.png",
  Lacoste: "brands/lacoste.png",
  Loewe: "brands/loewe.png",
  "Lorenzo Pazzaglia": "brands/lorenzo-pazzaglia.png",
  "Maison Martin Margiela": "brands/maison-martin-margiela.png",
  Mancera: "brands/mancera.png",
  Montblanc: "brands/montblanc.png",
  Nishane: "brands/nishane.png",
  "Paco Rabanne": "brands/paco-rabanne.png",
  "Parfums de Marly": "brands/parfums-de-marly.png",
  Prada: "brands/prada.png",
  "Ralph Lauren": "brands/ralph-lauren.png",
  "Salvatore Ferragamo": "brands/salvatore-ferragamo.png",
  Tous: "brands/tous.png",
  Valentino: "brands/valentino.png",
  Versace: "brands/versace.png",
  "Viktor&Rolf": "brands/viktor-and-rolf.png",
  Xerjoff: "brands/xerjoff.png",
  YSL: "brands/ysl.png",
  "Yves Saint Laurent": "brands/ysl.png",
  Zara: "brands/zara.png",
  Zoologist: "brands/zoologist.png",
};
