export const metadataAssets = {
  seasons: {
    spring: "/images/metadata/seasons/spring.svg",
    summer: "/images/metadata/seasons/summer.svg",
    fall: "/images/metadata/seasons/fall.svg",
    winter: "/images/metadata/seasons/winter.svg",
  },
  occasions: {
    day: "/images/metadata/occasions/day.svg",
    daily: "/images/metadata/occasions/day.svg",
    night: "/images/metadata/occasions/night.svg",
    office: "/images/metadata/occasions/office.svg",
    casual: "/images/metadata/occasions/casual.svg",
    date: "/images/metadata/occasions/date.svg",
    evening: "/images/metadata/occasions/evening.svg",
    formal: "/images/metadata/occasions/formal.svg",
    gym: "/images/metadata/occasions/gym.svg",
    club: "/images/metadata/occasions/club.svg",
    special: "/images/metadata/occasions/special.svg",
    vacation: "/images/metadata/occasions/vacation.svg",
  },
  vibes: {
    approachable: "/images/metadata/vibes/approachable.svg",
    aquatic: "/images/metadata/vibes/aquatic.svg",
    artistic: "/images/metadata/vibes/artistic.svg",
    bold: "/images/metadata/vibes/bold.svg",
    bright: "/images/metadata/vibes/bright.svg",
    calm: "/images/metadata/vibes/calm.svg",
    citrus: "/images/metadata/vibes/citrus.svg",
    classic: "/images/metadata/vibes/classic.svg",
    clean: "/images/metadata/vibes/clean.svg",
    confident: "/images/metadata/vibes/confident.svg",
    cozy: "/images/metadata/vibes/cozy.svg",
    dark: "/images/metadata/vibes/dark.svg",
    earthy: "/images/metadata/vibes/earthy.svg",
    easy: "/images/metadata/vibes/easy.svg",
    edgy: "/images/metadata/vibes/edgy.svg",
    elegant: "/images/metadata/vibes/elegant.svg",
    energetic: "/images/metadata/vibes/energetic.svg",
    fresh: "/images/metadata/vibes/fresh.svg",
    fruity: "/images/metadata/vibes/fruity.svg",
    green: "/images/metadata/vibes/green.svg",
    intense: "/images/metadata/vibes/intense.svg",
    luxurious: "/images/metadata/vibes/luxurious.svg",
    masculine: "/images/metadata/vibes/masculine.svg",
    "mass appealing": "/images/metadata/vibes/mass-appealing.svg",
    mediterranean: "/images/metadata/vibes/mediterranean.svg",
    modern: "/images/metadata/vibes/modern.svg",
    mysterious: "/images/metadata/vibes/mysterious.svg",
    natural: "/images/metadata/vibes/natural.svg",
    playful: "/images/metadata/vibes/playful.svg",
    powerful: "/images/metadata/vibes/powerful.svg",
    relaxed: "/images/metadata/vibes/relaxed.svg",
    seductive: "/images/metadata/vibes/seductive.svg",
    smooth: "/images/metadata/vibes/smooth.svg",
    soft: "/images/metadata/vibes/soft.svg",
    sophisticated: "/images/metadata/vibes/sophisticated.svg",
    sporty: "/images/metadata/vibes/sporty.svg",
    sweet: "/images/metadata/vibes/sweet.svg",
    tropical: "/images/metadata/vibes/tropical.svg",
    unique: "/images/metadata/vibes/unique.svg",
    versatile: "/images/metadata/vibes/versatile.svg",
    warm: "/images/metadata/vibes/warm.svg",
  },
  accords: {
    almond: "/images/metadata/accords/almond.svg",
    amber: "/images/metadata/accords/amber.svg",
    aquatic: "/images/metadata/accords/aquatic.svg",
    aromatic: "/images/metadata/accords/aromatic.svg",
    caramel: "/images/metadata/accords/caramel.svg",
    citrus: "/images/metadata/accords/citrus.svg",
    clean: "/images/metadata/accords/clean.svg",
    coconut: "/images/metadata/accords/coconut.svg",
    coffee: "/images/metadata/accords/coffee.svg",
    earthy: "/images/metadata/accords/earthy.svg",
    floral: "/images/metadata/accords/floral.svg",
    fresh: "/images/metadata/accords/fresh.svg",
    "fresh spicy": "/images/metadata/accords/fresh-spicy.svg",
    fruity: "/images/metadata/accords/fruity.svg",
    green: "/images/metadata/accords/green.svg",
    incense: "/images/metadata/accords/incense.svg",
    iris: "/images/metadata/accords/iris.svg",
    lavender: "/images/metadata/accords/lavender.svg",
    leather: "/images/metadata/accords/leather.svg",
    marine: "/images/metadata/accords/marine.svg",
    mineral: "/images/metadata/accords/mineral.svg",
    musky: "/images/metadata/accords/musky.svg",
    oakmoss: "/images/metadata/accords/oakmoss.svg",
    patchouli: "/images/metadata/accords/patchouli.svg",
    powdery: "/images/metadata/accords/powdery.svg",
    salty: "/images/metadata/accords/salty.svg",
    smoky: "/images/metadata/accords/smoky.svg",
    spicy: "/images/metadata/accords/spicy.svg",
    sweet: "/images/metadata/accords/sweet.svg",
    tobacco: "/images/metadata/accords/tobacco.svg",
    toffee: "/images/metadata/accords/toffee.svg",
    tropical: "/images/metadata/accords/tropical.svg",
    vanilla: "/images/metadata/accords/vanilla.svg",
    violet: "/images/metadata/accords/violet.svg",
    "warm spicy": "/images/metadata/accords/warm-spicy.svg",
    "white floral": "/images/metadata/accords/white-floral.svg",
    woody: "/images/metadata/accords/woody.svg",
  },
};
