export const metadataAssets = {
  seasons: {
    spring: "metadata/seasons/spring.svg",
    summer: "metadata/seasons/summer.svg",
    fall: "metadata/seasons/fall.svg",
    winter: "metadata/seasons/winter.svg",
  },
  occasions: {
    day: "metadata/occasions/day.svg",
    daily: "metadata/occasions/day.svg",
    night: "metadata/occasions/night.svg",
    office: "metadata/occasions/office.svg",
    casual: "metadata/occasions/casual.svg",
    date: "metadata/occasions/date.svg",
    evening: "metadata/occasions/evening.svg",
    formal: "metadata/occasions/formal.svg",
    gym: "metadata/occasions/gym.svg",
    club: "metadata/occasions/club.svg",
    special: "metadata/occasions/special.svg",
    vacation: "metadata/occasions/vacation.svg",
  },
  vibes: {
    approachable: "metadata/vibes/approachable.svg",
    aquatic: "metadata/vibes/aquatic.svg",
    artistic: "metadata/vibes/artistic.svg",
    bold: "metadata/vibes/bold.svg",
    bright: "metadata/vibes/bright.svg",
    calm: "metadata/vibes/calm.svg",
    citrus: "metadata/vibes/citrus.svg",
    classic: "metadata/vibes/classic.svg",
    clean: "metadata/vibes/clean.svg",
    confident: "metadata/vibes/confident.svg",
    cozy: "metadata/vibes/cozy.svg",
    dark: "metadata/vibes/dark.svg",
    earthy: "metadata/vibes/earthy.svg",
    easy: "metadata/vibes/easy.svg",
    edgy: "metadata/vibes/edgy.svg",
    elegant: "metadata/vibes/elegant.svg",
    energetic: "metadata/vibes/energetic.svg",
    fresh: "metadata/vibes/fresh.svg",
    fruity: "metadata/vibes/fruity.svg",
    green: "metadata/vibes/green.svg",
    intense: "metadata/vibes/intense.svg",
    luxurious: "metadata/vibes/luxurious.svg",
    masculine: "metadata/vibes/masculine.svg",
    "mass appealing": "metadata/vibes/mass-appealing.svg",
    mediterranean: "metadata/vibes/mediterranean.svg",
    modern: "metadata/vibes/modern.svg",
    mysterious: "metadata/vibes/mysterious.svg",
    natural: "metadata/vibes/natural.svg",
    playful: "metadata/vibes/playful.svg",
    powerful: "metadata/vibes/powerful.svg",
    relaxed: "metadata/vibes/relaxed.svg",
    seductive: "metadata/vibes/seductive.svg",
    smooth: "metadata/vibes/smooth.svg",
    soft: "metadata/vibes/soft.svg",
    sophisticated: "metadata/vibes/sophisticated.svg",
    sporty: "metadata/vibes/sporty.svg",
    sweet: "metadata/vibes/sweet.svg",
    tropical: "metadata/vibes/tropical.svg",
    unique: "metadata/vibes/unique.svg",
    versatile: "metadata/vibes/versatile.svg",
    warm: "metadata/vibes/warm.svg",
  },
  accords: {
    almond: "metadata/accords/almond.svg",
    amber: "metadata/accords/amber.svg",
    aquatic: "metadata/accords/aquatic.svg",
    aromatic: "metadata/accords/aromatic.svg",
    caramel: "metadata/accords/caramel.svg",
    citrus: "metadata/accords/citrus.svg",
    clean: "metadata/accords/clean.svg",
    coconut: "metadata/accords/coconut.svg",
    coffee: "metadata/accords/coffee.svg",
    earthy: "metadata/accords/earthy.svg",
    floral: "metadata/accords/floral.svg",
    fresh: "metadata/accords/fresh.svg",
    "fresh spicy": "metadata/accords/fresh-spicy.svg",
    fruity: "metadata/accords/fruity.svg",
    green: "metadata/accords/green.svg",
    incense: "metadata/accords/incense.svg",
    iris: "metadata/accords/iris.svg",
    lavender: "metadata/accords/lavender.svg",
    leather: "metadata/accords/leather.svg",
    marine: "metadata/accords/marine.svg",
    mineral: "metadata/accords/mineral.svg",
    musky: "metadata/accords/musky.svg",
    oakmoss: "metadata/accords/oakmoss.svg",
    patchouli: "metadata/accords/patchouli.svg",
    powdery: "metadata/accords/powdery.svg",
    salty: "metadata/accords/salty.svg",
    smoky: "metadata/accords/smoky.svg",
    spicy: "metadata/accords/spicy.svg",
    sweet: "metadata/accords/sweet.svg",
    tobacco: "metadata/accords/tobacco.svg",
    toffee: "metadata/accords/toffee.svg",
    tropical: "metadata/accords/tropical.svg",
    vanilla: "metadata/accords/vanilla.svg",
    violet: "metadata/accords/violet.svg",
    "warm spicy": "metadata/accords/warm-spicy.svg",
    "white floral": "metadata/accords/white-floral.svg",
    woody: "metadata/accords/woody.svg",
  },
};
