// Aurelian-owned es-MX display labels for shared-catalog fragrance accords
// and notes. This is editorial vocabulary specific to Aurelian's Spanish
// presentation, not generic Builder behavior -- it lives here, not in
// packages/builder, per the merchant-boundary decision (see ADR-0004/0007).
//
// Supplied to the shared Builder via `aurelianConfig.taxonomyLabels` (see
// merchant/config.js), which `createTranslator`'s generic `taxonomyLabels`
// override param resolves ahead of its own built-in dictionaries. The
// Builder never needs to know this vocabulary exists; it only knows how to
// look up a key in whatever override map a host supplies.
//
// Keys match the `taxonomy.<canonicalValue>` shape `translator.label()`
// looks up -- one entry per fragrance accord and per catalog note id
// currently defined in @discovery-box/catalog. Completeness against the
// live catalog is enforced by taxonomyLabels.test.js, not by this file
// itself.
export const aurelianTaxonomyLabels = {
  "taxonomy.almond": "Almendra",
  "taxonomy.amber": "Ámbar",
  "taxonomy.aquatic": "Acuático",
  "taxonomy.aromatic": "Aromático",
  "taxonomy.caramel": "Caramelo",
  "taxonomy.citrus": "Cítrico",
  "taxonomy.clean": "Limpio",
  "taxonomy.coconut": "Coco",
  "taxonomy.coffee": "Café",
  "taxonomy.earthy": "Terroso",
  "taxonomy.floral": "Floral",
  "taxonomy.fresh": "Fresco",
  "taxonomy.fresh spicy": "Fresco Especiado",
  "taxonomy.fruity": "Frutal",
  "taxonomy.green": "Verde",
  "taxonomy.incense": "Incienso",
  "taxonomy.iris": "Iris",
  "taxonomy.lavender": "Lavanda",
  "taxonomy.leather": "Cuero",
  "taxonomy.marine": "Marino",
  "taxonomy.mineral": "Mineral",
  "taxonomy.musky": "Almizclado",
  "taxonomy.oakmoss": "Musgo de Roble",
  "taxonomy.patchouli": "Pachulí",
  "taxonomy.powdery": "Polvoroso",
  "taxonomy.salty": "Salado",
  "taxonomy.smoky": "Ahumado",
  "taxonomy.spicy": "Especiado",
  "taxonomy.sweet": "Dulce",
  "taxonomy.tobacco": "Tabaco",
  "taxonomy.toffee": "Toffee",
  "taxonomy.tropical": "Tropical",
  "taxonomy.vanilla": "Vainilla",
  "taxonomy.violet": "Violeta",
  "taxonomy.warm spicy": "Cálido Especiado",
  "taxonomy.white floral": "Floral Blanco",
  "taxonomy.woody": "Amaderado",

  "taxonomy.lime": "Lima",
  "taxonomy.lemon": "Limón",
  "taxonomy.bergamot": "Bergamota",
  "taxonomy.jasmine": "Jazmín",
  "taxonomy.orange": "Naranja",
  "taxonomy.mandarinOrange": "Mandarina",
  "taxonomy.neroli": "Neroli",
  "taxonomy.seaNotes": "Notas Marinas",
  "taxonomy.calone": "Calone",
  "taxonomy.rosemary": "Romero",
  "taxonomy.peach": "Durazno",
  "taxonomy.freesia": "Fresia",
  "taxonomy.hyacinth": "Jacinto",
  "taxonomy.cyclamen": "Ciclamen",
  "taxonomy.coriander": "Cilantro",
  "taxonomy.rose": "Rosa",
  "taxonomy.nutmeg": "Nuez Moscada",
  "taxonomy.mignonette": "Reseda",
  "taxonomy.whiteMusk": "Almizcle Blanco",
  "taxonomy.cedar": "Cedro",
  "taxonomy.roseDeMai": "Rosa de Mayo",
  "taxonomy.clarySage": "Salvia Sclarea",
  "taxonomy.geranium": "Geranio",
  "taxonomy.musk": "Almizcle",
  "taxonomy.tonkaBean": "Haba Tonka",
  "taxonomy.powderyNotes": "Notas Polvorosas",
  "taxonomy.pineapple": "Piña",
  "taxonomy.lemonVerbena": "Verbena de Limón",
  "taxonomy.redApple": "Manzana Roja",
  "taxonomy.driedFruits": "Frutas Secas",
  "taxonomy.coumarin": "Cumarina",
  "taxonomy.sandalwood": "Sándalo",
  "taxonomy.mint": "Menta",
  "taxonomy.cardamom": "Cardamomo",
  "taxonomy.artemisia": "Artemisa",
  "taxonomy.cinnamon": "Canela",
  "taxonomy.orangeBlossom": "Azahar",
  "taxonomy.caraway": "Alcaravea",
  "taxonomy.candyApple": "Manzana Acaramelada",
  "taxonomy.ambroxan": "Ambroxan",
  "taxonomy.bitterOrange": "Naranja Amarga",
  "taxonomy.ginger": "Jengibre",
  "taxonomy.maninka": "Maninka",
  "taxonomy.woodyNotes": "Notas Amaderadas",
  "taxonomy.amberwood": "Madera Ambarina",
  "taxonomy.sicilianMandarin": "Mandarina Siciliana",
  "taxonomy.petitgrain": "Petitgrain",
  "taxonomy.grapefruit": "Toronja",
  "taxonomy.vetiver": "Vetiver",
  "taxonomy.lilyOfTheValley": "Lirio del Valle",
  "taxonomy.sage": "Salvia",
  "taxonomy.cloves": "Clavo de Olor",
  "taxonomy.citron": "Cidra",
  "taxonomy.figNectar": "Néctar de Higo",
  "taxonomy.pinkPepper": "Pimienta Rosa",
  "taxonomy.figTree": "Higuera",
  "taxonomy.benzoin": "Benjuí",
  "taxonomy.greenMandarin": "Mandarina Verde",
  "taxonomy.bloodOrange": "Naranja Sanguina",
  "taxonomy.spearmint": "Hierbabuena",
  "taxonomy.elemi": "Elemí",
  "taxonomy.olibanum": "Olíbano",
  "taxonomy.sichuanPepper": "Pimienta de Sichuan",
  "taxonomy.starAnise": "Anís Estrellado",
  "taxonomy.blackCurrant": "Grosella Negra",
  "taxonomy.chestnut": "Castaña",
  "taxonomy.guaiacWood": "Madera de Guayaco",
  "taxonomy.juniper": "Enebro",
  "taxonomy.peruBalsam": "Bálsamo de Perú",
  "taxonomy.cashmeran": "Cashmeran",
  "taxonomy.madagascarVanilla": "Vainilla de Madagascar",
  "taxonomy.akigalawood": "Akigalawood",
  "taxonomy.timur": "Timur",
  "taxonomy.osmanthus": "Osmanto",
  "taxonomy.pomarose": "Pomarose",
  "taxonomy.siamBenzoin": "Benjuí de Siam",
  "taxonomy.texasCedar": "Cedro de Texas",
  "taxonomy.virginiaCedar": "Cedro de Virginia",
  "taxonomy.orris": "Raíz de Lirio",
  "taxonomy.australianSandalwood": "Sándalo Australiano",
  "taxonomy.cypress": "Ciprés",
  "taxonomy.greenTea": "Té Verde",
  "taxonomy.galbanum": "Gálbano",
  "taxonomy.licorice": "Regaliz",
  "taxonomy.haitianVetiver": "Vetiver Haitiano",
  "taxonomy.greenApple": "Manzana Verde",
  "taxonomy.saffron": "Azafrán",
  "taxonomy.davana": "Davana",
  "taxonomy.opoponax": "Opopónaco",
  "taxonomy.ambermax": "Ambermax",
  "taxonomy.apple": "Manzana",
  "taxonomy.amylSalicylate": "Salicilato de Amilo",
  "taxonomy.ink": "Tinta",
  "taxonomy.seaSalt": "Sal Marina",
  "taxonomy.ambergris": "Ámbar Gris",
  "taxonomy.violetLeaf": "Hoja de Violeta",
  "taxonomy.bourbonVanilla": "Vainilla Bourbon",
  "taxonomy.fir": "Abeto",
  "taxonomy.brazilianRosewood": "Palo de Rosa Brasileño",
  "taxonomy.citruses": "Cítricos",
  "taxonomy.grass": "Pasto",
  "taxonomy.sugar": "Azúcar",
  "taxonomy.suede": "Gamuza",
  "taxonomy.cashmirwood": "Madera de Cachemira",
  "taxonomy.martini": "Martini",
  "taxonomy.gingerFlower": "Flor de Jengibre",
  "taxonomy.icedMango": "Mango Helado",
  "taxonomy.mango": "Mango",
  "taxonomy.mandarinOil": "Aceite de Mandarina",
  "taxonomy.lemonOil": "Aceite de Limón",
  "taxonomy.tangerine": "Tangerina",
  "taxonomy.ozone": "Ozono",
  "taxonomy.silverArmoise": "Artemisa Plateada",
  "taxonomy.patchouliNoir": "Pachulí Negro",
  "taxonomy.italianMandarin": "Mandarina Italiana",
  "taxonomy.roastedCoffeeBeans": "Granos de Café Tostado",
  "taxonomy.birchLeaf": "Hoja de Abedul",
  "taxonomy.pine": "Pino",
  "taxonomy.firBalsam": "Bálsamo de Abeto",
  "taxonomy.basil": "Albahaca",
  "taxonomy.moss": "Musgo",
  "taxonomy.cedarwood": "Madera de Cedro",
  "taxonomy.fingerLime": "Lima Caviar",
  "taxonomy.eucalyptus": "Eucalipto",
  "taxonomy.aldehydes": "Aldehídos",
  "taxonomy.mandarin": "Mandarina",
  "taxonomy.blackPepper": "Pimienta Negra",
  "taxonomy.pepper": "Pimienta",
  "taxonomy.bamboo": "Bambú",
  "taxonomy.birch": "Abedul",
  "taxonomy.chinotto": "Chinotto",
  "taxonomy.cranberry": "Arándano Rojo",
  "taxonomy.labdanum": "Ládano",
  "taxonomy.magnolia": "Magnolia",
  "taxonomy.mahogany": "Caoba",
  "taxonomy.whitePepper": "Pimienta Blanca",
  "taxonomy.wormwood": "Ajenjo",
  "taxonomy.anise": "Anís",
  "taxonomy.blackVanilla": "Vainilla Negra",
  "taxonomy.fennel": "Hinojo",
  "taxonomy.fig": "Higo",
  "taxonomy.frangipani": "Frangipani",
  "taxonomy.fruityNotes": "Notas Frutales",
  "taxonomy.greenMango": "Mango Verde",
  "taxonomy.carrotSeeds": "Semillas de Zanahoria",
  "taxonomy.angelica": "Angélica",
  "taxonomy.cumin": "Comino",
  "taxonomy.mineralNotes": "Notas Minerales",
  "taxonomy.oak": "Roble",
  "taxonomy.oliveBlossom": "Flor de Olivo",
  "taxonomy.orientalNotes": "Notas Orientales",
  "taxonomy.passionFruit": "Maracuyá",
  "taxonomy.plum": "Ciruela",
  "taxonomy.spicyNotes": "Notas Especiadas",
  "taxonomy.truffle": "Trufa",
  "taxonomy.whiteLotus": "Loto Blanco",
  "taxonomy.spices": "Especias",
  "taxonomy.leatherwood": "Madera de Cuero",
  "taxonomy.rum": "Ron",
  "taxonomy.amaretto": "Amaretto",
};
