import { DEFAULT_BUILDER_THEME_COLORS } from "../theme/builderTheme.js";

export const defaultBuilderConfig = {
  locale: "en-US",
  software: {
    name: "Decant Builder",
  },
  brand: {
    businessName: "",
    displayName: "",
    shortName: "",
    heading: "",
  },
  analytics: {
    merchantId: "default",
  },
  commerce: {
    currency: "MXN",
    locale: "en-US",
    currencySymbol: "$",
    pointValue: 100,
    totalLabel: "Order Total",
  },
  recovery: {
    title: "Something unexpected happened.",
    description: "{productName} could not finish loading. Your saved box may still be available.",
    reloadLabel: "Reload Builder",
    clearSavedLabel: "Clear Saved Box and Reload",
  },
  box: {
    minSelectableSlots: 6,
    maxSelectableSlots: 14,
    defaultTargetSlots: 14,
    totalPhysicalSlots: 16,
    bonusSlotCount: 2,
    minPoints: 12,
  },
  curatorBonus: {
    enabled: true,
    targetPoints: 12,
    label: "Curator Bonus",
    rewardLabel: "Bonus Fragrance",
    rewardPluralLabel: "Bonus Fragrances",
    progressCopy: {
      unlocked: "Curator Bonus Unlocked",
      lockedCompletion: "Complete your Discovery Box",
      lockedStrategy: "Unlock Curator Bonus and choose your reward strategy.",
      pickValue: "Equivalent to 2 bonus points.",
      similarSelected: "Selected based on your fragrance preferences.",
      complementSelected: "Selected to complement your collection.",
    },
    preferences: {
      complement: {
        label: "Complement My Collection",
        description: "Curator picks selected to balance your box.",
      },
      similar: {
        label: "Similar To My Picks",
        description: "Curator picks inspired by your current taste.",
      },
    },
    defaultPreference: "complement",
  },
  collectionCard: {
    enabled: true,
    brandHeading: "",
    ariaLabel: "collection card",
    boxAriaLabel: "Rendered Discovery Box",
    filenamePrefix: "collection",
    exportWidth: 1080,
    exportHeight: 1920,
    downloadLabel: "Download PNG",
    shareLabel: "Share Card",
    previewLabel: "Preview Card",
    generatingLabel: "Generating...",
    downloadedStatus: "Collection Card downloaded.",
    sharedStatus: "Collection Card shared.",
    unavailableShareStatus: "Native image sharing is unavailable. Download the PNG instead.",
    unavailableShareFallbackStatus: "Native sharing is unavailable. Download the PNG instead.",
    renderFailureStatus: "The Collection Card could not be rendered. Please try again.",
    createFailureStatus: "Could not create the Collection Card PNG.",
    shareTitle: "My Collection",
    shareText: "A curated collection.",
    tooltip: "Export an editorial card for your finished Discovery Box.",
    footer: "Curated for discovery.",
    curatorBonusIncludedLabel: "Curator Bonus Included",
    curatorBonusAvailableLabel: "Curator Bonus Available",
    curatorBonusUnlockedCopy: "Mystery selections remain wrapped.",
    curatorBonusLockedCopy: "Complete your Discovery Box to unlock mystery selections.",
  },
  finalization: {
    mode: "whatsapp",
    whatsappNumber: "",
    orderCodePrefix: "DB",
    customerDefaults: {
      name: "",
      city: "",
      notes: "",
    },
    customerFieldLabels: {
      name: "Customer name",
      city: "City",
      notes: "Notes",
    },
    requiredFields: ["name", "city"],
    visibleCustomerFields: ["name", "city", "notes"],
    customerFieldMaxLengths: { name: 120, city: 120, notes: 500 },
    actionLabel: "Finalize Box",
    requiredCustomerCopy: "Enter customer name and city before finalizing.",
    whatsapp: {
      greeting: "Hello {businessName}, I would like to finalize my Discovery Box order.",
      closing: "Please confirm availability and next steps. Thank you.",
      blockedCopied: "WhatsApp was blocked. The order message was copied; use the button below to open WhatsApp.",
      blockedManual: "WhatsApp was blocked. Use the button below to open WhatsApp manually.",
      openingCopied: "Opening WhatsApp to message {businessName}. Order message copied.",
      opening: "Opening WhatsApp to message {businessName}.",
      manualOpenLabel: "Open WhatsApp manually",
    },
    messageLabels: {
      customer: "Customer",
      city: "City",
      notes: "Notes",
      selectedFragrances: "Selected fragrances:",
      totalSlots: "Total slots",
      totalPoints: "Total points",
      orderTotal: "Order total",
      curatorBonus: "Curator Bonus",
      curatorStyle: "Curator Style",
      unlocked: "Unlocked",
      notUnlocked: "Not unlocked",
    },
  },
  persistence: {
    storageKey: "builder-state",
    schemaVersion: 1,
    fragranceDetailsHintKey: "fragranceDetailsHintSeen",
    discoveryIntroSeenKey: "discoveryBoxIntroSeen",
    restoreMessage: "Your previous box has been restored.",
  },
  features: {
    recommendations: true,
    collectionIntelligence: true,
    collectionDna: true,
    dnaExplorer: true,
    curatorBonus: true,
    review: true,
    collectionCard: true,
    nativeShare: true,
    whatsappFinalization: true,
    scentLibrary: true,
    discoveryCoachmark: true,
  },
  copy: {
    heroTitle: "Build your fragrance box",
    heroDescription:
      "Select up to {maxSelectableSlots} decants, explore different moods, and see the value of your box update in real time.",
    boxPanelTitle: "My Box",
    clearBuilderLabel: "Clear Box",
    introAriaLabel: "Discovery Box introduction",
    introTitle: "Welcome to Discovery Box",
    introDescription: "Reach 12 points to unlock Curator Bonus selections.",
    onboardingTitle: "Welcome to Discovery Box",
    onboardingIntro: "Choose how you want to start building your Discovery Box.",
    onboardingDesktopDescription:
      "Build manually from the catalog or let Composer prepare a proposal from your preferences.",
    onboardingManualTitle: "Explore the catalog yourself",
    onboardingManualDescription:
      "Browse fragrances, open details, and add each pick by hand.",
    onboardingManualAction: "Explore Catalog",
    onboardingComposerTitle: "Let Composer build a proposal",
    onboardingComposerDescription:
      "Choose preferences and review a complete box proposal before applying it.",
    onboardingComposerAction: "Use Composer",
    onboardingDesktopComposerAction: "Try Composer",
    onboardingSwitchNote: "You can switch between both methods at any time.",
    onboardingCloseLabel: "Close onboarding",
    reviewButtonLabel: "Review My Box",
    reviewIncompletePrefix: "Need",
    reviewIncompleteFallback: "minimum requirements",
    reviewCuratorUnlockedCopy: "Your curator pick remains wrapped until reveal.",
    reviewCuratorLockedCopy: "Unlocks when your Discovery Box is complete.",
  },
  theme: {
    colors: DEFAULT_BUILDER_THEME_COLORS,
  },
};
