import { createBuilderConfig } from "./createBuilderConfig.js";

export const discoveryDecantsConfig = createBuilderConfig({
  brand: {
    businessName: "Discovery Decants",
    displayName: "Discovery Decants",
    shortName: "Discovery",
    heading: "Discovery Decants",
  },
  commerce: {
    currency: "MXN",
    locale: "en-US",
    currencySymbol: "$",
    pointValue: 100,
    totalLabel: "Estimated Total",
  },
  box: {
    minSelectableSlots: 6,
    maxSelectableSlots: 14,
    defaultTargetSlots: 14,
    totalPhysicalSlots: 16,
    bonusSlotCount: 2,
    minPoints: 12,
  },
  curatorBonus: {
    enabled: true,
    targetPoints: 12,
    label: "Curator Bonus",
    rewardLabel: "Bonus Fragrance",
    rewardPluralLabel: "Bonus Fragrances",
    progressCopy: {
      unlocked: "Curator Bonus Unlocked",
      lockedCompletion: "Complete your Discovery Box",
      lockedStrategy: "Unlock Curator Bonus and choose your reward strategy.",
      pickValue: "Equivalent to 2 bonus points.",
      similarSelected: "Selected based on your fragrance preferences.",
      complementSelected: "Selected to complement your collection.",
    },
    preferences: {
      complement: {
        label: "Complement My Collection",
        description: "Curator picks selected to balance your box.",
      },
      similar: {
        label: "Similar To My Picks",
        description: "Curator picks inspired by your current taste.",
      },
    },
    defaultPreference: "complement",
  },
  collectionCard: {
    enabled: true,
    brandHeading: "Discovery Decants",
    ariaLabel: "Discovery Decants collection card",
    boxAriaLabel: "Rendered Discovery Box",
    filenamePrefix: "discovery-decants",
    exportWidth: 1080,
    exportHeight: 1920,
    downloadLabel: "Download PNG",
    shareLabel: "Share Card",
    previewLabel: "Preview Card",
    generatingLabel: "Generating...",
    downloadedStatus: "Collection Card downloaded.",
    sharedStatus: "Collection Card shared.",
    unavailableShareStatus: "Native image sharing is unavailable. Download the PNG instead.",
    unavailableShareFallbackStatus: "Native sharing is unavailable. Download the PNG instead.",
    renderFailureStatus: "The Collection Card could not be rendered. Please try again.",
    createFailureStatus: "Could not create the Collection Card PNG.",
    shareTitle: "My Discovery Decants Collection",
    shareText: "A curated Discovery Decants collection.",
    tooltip: "Export an editorial card for your finished Discovery Box.",
    footer: "Curated for discovery.",
    curatorBonusIncludedLabel: "Curator Bonus Included",
    curatorBonusAvailableLabel: "Curator Bonus Available",
    curatorBonusUnlockedCopy: "Mystery selections remain wrapped.",
    curatorBonusLockedCopy: "Complete your Discovery Box to unlock mystery selections.",
  },
  finalization: {
    mode: "whatsapp",
    whatsappNumber: "528129800010",
    orderCodePrefix: "DB",
    customerDefaults: {
      name: "",
      city: "",
      notes: "",
    },
    customerFieldLabels: {
      name: "Customer name",
      city: "City",
      notes: "Notes",
    },
    requiredFields: ["name", "city"],
    whatsapp: {
      greeting: "Hello {businessName}, I would like to finalize my Discovery Box order.",
      closing: "Please confirm availability and next steps. Thank you.",
      blockedCopied: "WhatsApp was blocked. The order message was copied; use the button below to open WhatsApp.",
      blockedManual: "WhatsApp was blocked. Use the button below to open WhatsApp manually.",
      openingCopied: "Opening WhatsApp to message {businessName}. Order message copied.",
      opening: "Opening WhatsApp to message {businessName}.",
      manualOpenLabel: "Open WhatsApp manually",
    },
  },
  persistence: {
    storageKey: "decant-builder-v1",
    schemaVersion: 1,
    fragranceDetailsHintKey: "fragranceDetailsHintSeen",
    discoveryIntroSeenKey: "discoveryBoxIntroSeen",
    restoreMessage: "Your previous box has been restored.",
  },
  features: {
    recommendations: true,
    collectionIntelligence: true,
    collectionDna: true,
    dnaExplorer: true,
    curatorBonus: true,
    review: true,
    collectionCard: true,
    nativeShare: true,
    whatsappFinalization: true,
    scentLibrary: true,
  },
  copy: {
    heroTitle: "Build your fragrance box",
    heroDescription:
      "Select up to {maxSelectableSlots} decants, explore different moods, and see the value of your box update in real time.",
    boxPanelTitle: "My Box",
    clearBuilderLabel: "Clear Builder",
    introAriaLabel: "Discovery Box introduction",
    introButtonAriaLabel: "Show Discovery Box introduction",
    introTitle: "Welcome to Discovery Box",
    introDescription: "Reach 12 points to unlock Curator Bonus selections.",
    reviewButtonLabel: "Review My Box",
    reviewIncompletePrefix: "Need",
    reviewIncompleteFallback: "minimum requirements",
    reviewCuratorUnlockedCopy: "Your curator pick remains wrapped until reveal.",
    reviewCuratorLockedCopy: "Unlocks when your Discovery Box is complete.",
  },
});
