export const ANALYTICS_EVENTS = Object.freeze({
  APP_LOADED: "app_loaded",
  MERCHANT_EXPERIENCE_LOADED: "merchant_experience_loaded",
  PERFUME_ADDED: "perfume_added",
  PERFUME_REMOVED: "perfume_removed",
  BOX_CLEARED: "box_cleared",
  SEARCH_PERFORMED: "search_performed",
  FILTER_CHANGED: "filter_changed",
  SORT_CHANGED: "sort_changed",
  FRAGRANCE_DETAILS_OPENED: "fragrance_details_opened",
  COMPOSER_OPENED: "composer_opened",
  COMPOSER_GENERATION_STARTED: "composer_generation_started",
  COMPOSER_PROPOSAL_GENERATED: "composer_proposal_generated",
  COMPOSER_GENERATION_FAILED: "composer_generation_failed",
  PROPOSAL_ALTERNATIVE_VIEWED: "proposal_alternative_viewed",
  PROPOSAL_APPLIED: "proposal_applied",
  PROPOSAL_DISMISSED: "proposal_dismissed",
  REVIEW_OPENED: "review_opened",
  REVIEW_VALIDATION_FAILED: "review_validation_failed",
  ORDER_FINALIZATION_STARTED: "order_finalization_started",
  ORDER_FINALIZATION_SUCCEEDED: "order_finalization_succeeded",
  ORDER_FINALIZATION_FAILED: "order_finalization_failed",
  CURATOR_BONUS_UNLOCKED: "curator_bonus_unlocked",
  PERSISTENCE_RECOVERY_USED: "persistence_recovery_used",
  RUNTIME_ERROR_BOUNDARY_SHOWN: "runtime_error_boundary_shown",
});

export const ANALYTICS_EVENT_NAMES = Object.freeze(Object.values(ANALYTICS_EVENTS));

export const COMMON_CONTEXT_KEYS = Object.freeze([
  "merchantId",
  "locale",
  "softwareName",
  "flowId",
  "source",
]);

export const EVENT_PAYLOAD_KEYS = Object.freeze({
  [ANALYTICS_EVENTS.APP_LOADED]: ["selectedSlotCount", "source"],
  [ANALYTICS_EVENTS.MERCHANT_EXPERIENCE_LOADED]: ["source"],
  [ANALYTICS_EVENTS.PERFUME_ADDED]: [
    "perfumeId",
    "points",
    "source",
    "slotCountAfter",
    "totalPointsAfter",
  ],
  [ANALYTICS_EVENTS.PERFUME_REMOVED]: [
    "perfumeId",
    "source",
    "slotCountAfter",
    "totalPointsAfter",
  ],
  [ANALYTICS_EVENTS.BOX_CLEARED]: [
    "slotCountBefore",
    "totalPointsBefore",
    "curatorBonusUnlockedBefore",
    "source",
  ],
  [ANALYTICS_EVENTS.SEARCH_PERFORMED]: [
    "queryLength",
    "resultsCount",
    "activeFilterCount",
    "sortOption",
    "source",
  ],
  [ANALYTICS_EVENTS.FILTER_CHANGED]: [
    "category",
    "value",
    "isCleared",
    "resultsCount",
    "source",
  ],
  [ANALYTICS_EVENTS.SORT_CHANGED]: ["sortOption", "resultsCount", "source"],
  [ANALYTICS_EVENTS.FRAGRANCE_DETAILS_OPENED]: [
    "perfumeId",
    "visibleIndex",
    "visibleCount",
    "source",
  ],
  [ANALYTICS_EVENTS.COMPOSER_OPENED]: [
    "slotCount",
    "totalPoints",
    "requestedBudgetPoints",
    "requestedStyle",
    "source",
  ],
  [ANALYTICS_EVENTS.COMPOSER_GENERATION_STARTED]: [
    "requestedBudgetPoints",
    "requestedStyle",
    "selectedSeasons",
    "selectedOccasions",
    "selectedVibes",
    "slotCountBefore",
    "totalPointsBefore",
    "source",
  ],
  [ANALYTICS_EVENTS.COMPOSER_PROPOSAL_GENERATED]: [
    "requestedBudgetPoints",
    "requestedStyle",
    "selectedSeasons",
    "selectedOccasions",
    "selectedVibes",
    "proposalPerfumeIds",
    "proposalSlotCount",
    "proposalPoints",
    "isPartial",
    "alternativeCount",
    "durationMs",
    "source",
  ],
  [ANALYTICS_EVENTS.COMPOSER_GENERATION_FAILED]: [
    "errorCategory",
    "durationMs",
    "source",
  ],
  [ANALYTICS_EVENTS.PROPOSAL_ALTERNATIVE_VIEWED]: [
    "slotId",
    "slotIndex",
    "direction",
    "alternativeIndex",
    "alternativeCount",
    "perfumeId",
    "source",
  ],
  [ANALYTICS_EVENTS.PROPOSAL_APPLIED]: [
    "proposalPerfumeIds",
    "replacedPerfumeIds",
    "slotCountAfter",
    "totalPointsAfter",
    "source",
  ],
  [ANALYTICS_EVENTS.PROPOSAL_DISMISSED]: [
    "proposalPerfumeIds",
    "proposalSlotCount",
    "source",
  ],
  [ANALYTICS_EVENTS.REVIEW_OPENED]: [
    "slotCount",
    "totalPoints",
    "orderTotal",
    "curatorBonusUnlocked",
    "source",
  ],
  [ANALYTICS_EVENTS.REVIEW_VALIDATION_FAILED]: ["failedFields", "source"],
  [ANALYTICS_EVENTS.ORDER_FINALIZATION_STARTED]: [
    "slotCount",
    "totalPoints",
    "orderTotal",
    "curatorBonusUnlocked",
    "channel",
    "source",
  ],
  [ANALYTICS_EVENTS.ORDER_FINALIZATION_SUCCEEDED]: [
    "slotCount",
    "totalPoints",
    "orderTotal",
    "curatorBonusUnlocked",
    "channel",
    "copiedToClipboard",
    "source",
  ],
  [ANALYTICS_EVENTS.ORDER_FINALIZATION_FAILED]: [
    "slotCount",
    "totalPoints",
    "orderTotal",
    "curatorBonusUnlocked",
    "channel",
    "errorCategory",
    "copiedToClipboard",
    "source",
  ],
  [ANALYTICS_EVENTS.CURATOR_BONUS_UNLOCKED]: [
    "slotCount",
    "totalPoints",
    "preference",
    "source",
  ],
  [ANALYTICS_EVENTS.PERSISTENCE_RECOVERY_USED]: [
    "slotCount",
    "curatorBonusPreference",
    "source",
  ],
  [ANALYTICS_EVENTS.RUNTIME_ERROR_BOUNDARY_SHOWN]: ["errorCategory", "source"],
});

export const PROHIBITED_ANALYTICS_KEYS = Object.freeze([
  "name",
  "customerName",
  "city",
  "notes",
  "phone",
  "phoneNumber",
  "whatsappNumber",
  "message",
  "messageBody",
  "whatsappMessage",
  "query",
  "searchQuery",
  "url",
  "stack",
  "errorStack",
]);
